spring.application.name=langley-backend

# Server Configuration
server.port=8081

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/langley_db
spring.datasource.username=karthik
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Pretty print JSON
spring.jackson.serialization.indent-output=true

# Logging
logging.level.com.langley.hospital=INFO
logging.level.org.springframework.web=WARN
