@LangleyGeneralGateway_HostAddress = http://localhost:8083

GET {{LangleyGeneralGateway_HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{LangleyGeneralGateway_HostAddress}}/api/langleygeneral/patients
